apiVersion: v1
data:
  nginx.conf: |-
    user nginx;
    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
        server {
            listen 80;
            server_name localhost;

            location / {
                return 200 "Hello from Evgenij in YC-Sirius cluster!\n";
            }
        }
    }
immutable: false
kind: ConfigMap
metadata:
  creationTimestamp: "2026-02-18T16:05:25Z"
  name: main-nginx-config
  namespace: edu-evgenij-kondratev
  resourceVersion: "207681604"
  uid: 3a5d01cc-89bd-4b1f-b826-bb9e19d164dc
