apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-02-18T16:05:25Z"
  finalizers:
  - ingress.ya.ru/final
  name: main-nginx
  namespace: edu-evgenij-kondratev
  resourceVersion: "207606234"
  uid: 8c755b02-1370-4103-bf13-6fdcd13c25df
spec:
  clusterIP: 10.96.179.20
  clusterIPs:
  - 10.96.179.20
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31368
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: main-nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
