apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  labels:
    app: django
    app.kubernetes.io/name: django
    app.kubernetes.io/component: maintenance
    app.kubernetes.io/part-of: k8s-test-django
spec:
  schedule: "0 3 * * *"   # каждый день в 03:00
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: django
        spec:
          restartPolicy: Never
          containers:
            - name: clearsessions
              image: django_unit_app:latest
              imagePullPolicy: IfNotPresent
              command: ["python", "/app/src/manage.py", "clearsessions"]
              env:
                - name: DEBUG
                  value: "False"
                - name: ALLOWED_HOSTS
                  value: "*"
              envFrom:
                - secretRef:
                    name: django-secrets
